---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "172.31.32.33"}]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 256

suites:
  - name: default
    run_list:
      - recipe[roshicookbook::default]
    attributes:
