name 'roshicookbook'
maintainer 'David Jee (cskstrngth)'
maintainer_email 'cskstrngth@gmail.com'
license 'all_rights'
description 'Installs/Configures a roshi stack'
long_description 'Installs/Configures a simple CRDT stack based on roshi'
version '0.1.0'

depends 'apt', '~> 3.0.0'
depends 'firewall', '~> 2.5.0'
depends 'docker', '~> 2.0'
